=== hpcc-systems/HPCC-Platform/initfiles/componentfiles/configschema/templates/schema/ModTemplateSchema.json
{
    "$schema" : "http://json-schema.org/draft-04/schema#",
    "description" : "Schema for validating environment modification template",
    "type" : "object",
    "properties" : {
        "name" : {
            "type" : "string"
        },
        "description" : {
            "type" : "string"
        },
        "type" : {
            "type" : "string",
            "enum" : [
                "new",
                "modification"
            ]
        },
        "subtype" : {
            "type" : "string"
        },
        "inputs" : {
            "type" : "array",
            "minItems" : 0,
            "items" : {
                "type" : "object",
                "properties" : {
                    "name" : {
                        "type" : "string"
                    },
                    "type" : {
                        "type" : "string",
                        "enum" : [
                            "string",
                            "iprange",
                            "ipaddress",
                            "hostname"
                        ]
                    },
                    "prompt" : {
                        "type" : "string"
                    },
                    "description" : {
                        "type" : "string"
                    },
                    "tooltip" : {
                        "type" : "string"
                    },
                    "value" : {
                        "type" : "string"
                    },
                    "non_user_input" : {
                        "type" : "boolean"
                    },
                    "prepared_value" : {
                        "type" : "string"
                    }
                },
                "required" : [
                    "name",
                    "type"
                ]
            }
        },
        "rules" : {
            "type" : "object"
        },
        "operations" : {
            "type" : "array",
            "minItems" : 0,
            "items" : { "$ref" : "#/definitions/operation"}
        }
    },
    "required" : [
        "name",
        "type",
        "operations"
    ],

    "definitions" : {

        "operation" : {
            "type" : "object",
            "properties" : {
                "action" : {
                    "type" : "string"
                },
                "save_nodeid" : {
                    "type" : "string"
                },
                "path" : {
                    "type" : "string"
                },
                "parent_nodeid" : {
                    "type" : "string"
                },
                "node_type" : {
                    "type" : "string"
                },
                "count" : {
                    "type" : "string"
                },
                "start_index" : {
                    "type" : "string"
                },
                "attributes" : {
                    "$ref" : "#/definitions/attribute_values"
                }
            },
            "allOf" : [
                {
                    "oneOf" : [

                        {
                            "properties" : {
                                "action" : { "enum" : [ "create_node"]}
                            },
                            "required" : ["node_type"]
                        },
                        {
                            "properties" : {
                                "action" : { "enum" : ["modify_node", "noop"]}
                            }
                        }
                    ]
                },
                {
                    "oneOf" : [
                        { "required" : [ "path" ]},
                        { "required" : [ "parent_nodeid" ]}
                    ]
                },
                {
                    "required" : ["action"]
                }
            ]

        },

        "attribute_value" : {
            "type" : "object",
            "properties" : {
                "name" : {
                    "type" : "string"
                },
                "value" : {
                    "type" : "string"
                },
                "save_value" : {
                    "type" : "string"
                },
                "do_not_set" : {
                    "type" : "boolean"
                }
            },
            "required" : ["name", "value"]
        },

        "attribute_values" : {
            "type" : "array",
            "items" : {
                "$ref" : "#/definitions/attribute_value"
            }
        }
    }
}

=== hpcc-systems/HPCC-Platform/testing/unittests/configmgr/templates/SubstitutionTest-1.json
{
    "name" : "test",
    "type" : "modification",
    "description" : "add a subchild to an existing node in an environment",
    "inputs" : [
        {
            "name" : "name",
            "type" : "string",
            "value" : "myname"
        },
        {
            "name" : "numsystems",
            "type" : "string",
            "value" : "10"
        },
        {
            "name" : "ccnum",
            "type" : "string",
            "value" : "2"
        },
        {
            "name" : "hwips",
            "type" : "iprange",
            "value" : "1.2.3.1-10"
        },
        {
            "name" : "baseip",
            "type" : "ipaddress",
            "value" : "1.2.3.1"
        },
        {
            "name" : "systemips",
            "type" : "iprange",
            "prepared_value" : "{{baseip}}*{{numsystems}}"
        }
    ],
    "operations" : [
        {
            "action" : "noop",
            "path" : "/Root/Child1",
            "count" : "{{numsystems}}",
            "attributes" : [
                {
                    "name" : "name",
                    "value" : "{{name}}"
                },
                {
                    "name" : "ipaddress",
                    "value" : "{{hwips}}"
                },
                {
                    "name" : "daliIp",
                    "value" : "{{hwips[0]}}"
                },
                {
                    "name" : "ccIp",
                    "value" : "{{hwips[{{numsystems}}-{{ccnum}}]}}"
                }
            ]
        }
    ]
}

=== hpcc-systems/HPCC-Platform/testing/unittests/configmgr/templates/OperationsTest1.json
{
    "name" : "test",
    "type" : "modification",
    "description" : "add a subchild to an existing node in an environment",
    "inputs" : [
        {
            "name" : "attr1",
            "type" : "string",
            "value" : "attr1Value"
        },
        {
            "name" : "attr2",
            "type" : "string",
            "value" : "444"
        }
    ],
    "operations" : [
        {
            "action" : "create_node",
            "path" : "/Root/Child1",
            "node_type" : "subchild1",
            "attributes" : [
                {
                    "name" : "attr1",
                    "value" : "{{attr1}}"
                },
                {
                    "name" : "attr2",
                    "value" : "{{attr2}}"
                }
            ]
        }
    ]
}
